### ISSUE TITLE
'/class' aka '/professor' command for sentiment analysis

### ISSUE THREAD

**Issue by jaynopponep** [BYTE-Club-CCNY/Silvercord#3]
Main idea here is to deliver a response that describes how a specific course or professor is based on Rate My Professor reviews. **Please make a separate branch**
## Deliverables:
- [x] Explore methods of scraping by directly scraping ourselves with BS4, and/or using the following API wrappers I found: [Nobelz RMP](https://github.com/Nobelz/RateMyProfessorAPI); [MTU Courses RMP](https://github.com/Michigan-Tech-Courses/rate-my-professors)
- [ ] '/class' command is already built. Write an API function that uses one of the RMP api's above that takes in professor name as an input, and returns the RMP link formatted as https://ratemyprofessor.com/professors/[PROFESSOR_ID_HERE]. Should be easy.
- [ ] Using the written API function from above, work with the existing '/professor' implementation to pass over the link to the llm.py. Pipeline should now be "professor name" taken from '/professor' -> API function converting it into a link -> send out link to llm.py (should run something like python llm.py [link])
- [ ] Do research for me on NLTK Sentinment Analysis & how we can implement it into our /professor, then we'll work together on actually implementing to improve the AI response
- [ ] Unit tests demoing at least 6 professor names. Each test should take the professor name and then return their corresponding link.

**Comment by jaynopponep** [comment]
Keeping record of no longer needed deleted tasks:
~~- [ ] If you choose to use BS4, notice that all the comments/reviews are listed in a '< ul >' and each comment is stored in every-other '< li >' (if we don't include the ads). When scraping, try to implement logic so that you only scrape what's relevant obviously.~~
~~- [ ] If you choose to use the API wrappers, for an MVP of this command, we can just work with the basic info (overall ratings, tags, etc.)~~

**Comment by jaynopponep** [comment]
All deliverables fully updated @dddictionary

**Comment by dddictionary** [comment]
## Updated Deliverables:
- [ ] Restructure the project folder structure: should be `index.js` in root with folders like commands, events, utils, logs for anything else. 
- [ ] Create admin command to sync commands instead of always syncing at startup, to stop ratelimit
